package visao;

public class FRMCentral extends javax.swing.JFrame {

    /**
     * Creates new form Central
     */
    public FRMCentral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMICadastroFerramenta = new javax.swing.JMenuItem();
        jMICadastroAmigo = new javax.swing.JMenuItem();
        jMIEmprestimoFerramenta = new javax.swing.JMenuItem();
        jMIConcluirEmprestimo = new javax.swing.JMenuItem();
        jMIGerenciamentoFerramentas = new javax.swing.JMenuItem();
        jMIGerenciamentoAmigos = new javax.swing.JMenuItem();
        jMITestePopUp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIRelatorioAtivo = new javax.swing.JMenuItem();
        jMIRelatorioFerramenta = new javax.swing.JMenuItem();
        jMIRelatorioToods = new javax.swing.JMenuItem();
        jMIEstatisticas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Central de Cadastros");

        jLabel1.setText("Bem Vindo!");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));

        jMenu1.setText("Opções");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMICadastroFerramenta.setText("Cadastro de Ferramentas");
        jMICadastroFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroFerramentaActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastroFerramenta);

        jMICadastroAmigo.setText("Cadastro de Amigos");
        jMICadastroAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastroAmigoActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastroAmigo);

        jMIEmprestimoFerramenta.setText("Empréstimo de Ferramentas");
        jMIEmprestimoFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEmprestimoFerramentaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIEmprestimoFerramenta);

        jMIConcluirEmprestimo.setText("Concluir Empréstimo");
        jMIConcluirEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConcluirEmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(jMIConcluirEmprestimo);

        jMIGerenciamentoFerramentas.setText("Gerenciamento de Ferramentas");
        jMIGerenciamentoFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciamentoFerramentasActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGerenciamentoFerramentas);

        jMIGerenciamentoAmigos.setText("Gerenciamento de Amigos");
        jMIGerenciamentoAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciamentoAmigosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGerenciamentoAmigos);

        jMITestePopUp.setText("Teste PopUp");
        jMenu1.add(jMITestePopUp);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jMIRelatorioAtivo.setText("Empréstimos Ativos");
        jMIRelatorioAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioAtivoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIRelatorioAtivo);

        jMIRelatorioFerramenta.setText("Ferramentas e Custos");
        jMIRelatorioFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioFerramentaActionPerformed(evt);
            }
        });
        jMenu2.add(jMIRelatorioFerramenta);

        jMIRelatorioToods.setText("Todos os Empréstimos");
        jMIRelatorioToods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioToodsActionPerformed(evt);
            }
        });
        jMenu2.add(jMIRelatorioToods);

        jMIEstatisticas.setText("Estatísticas");
        jMIEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEstatisticasActionPerformed(evt);
            }
        });
        jMenu2.add(jMIEstatisticas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIEmprestimoFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEmprestimoFerramentaActionPerformed
       FRMEmprestimoFerramenta emprestimoFerramenta = new FRMEmprestimoFerramenta();
    emprestimoFerramenta.setVisible(true);
    }//GEN-LAST:event_jMIEmprestimoFerramentaActionPerformed

    private void jMIRelatorioAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioAtivoActionPerformed
        FRMRelatorioAtivo relatorioAtivo = new FRMRelatorioAtivo();
    relatorioAtivo.setVisible(true);
    }//GEN-LAST:event_jMIRelatorioAtivoActionPerformed

    private void jMIRelatorioFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioFerramentaActionPerformed
       FRMRelatorioFerramenta relatorioFerramenta = new FRMRelatorioFerramenta();
       relatorioFerramenta.setVisible(true);
    }//GEN-LAST:event_jMIRelatorioFerramentaActionPerformed

    private void jMICadastroFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroFerramentaActionPerformed
     FRMCadastroFerramenta cadastroFerramenta = new FRMCadastroFerramenta();
    cadastroFerramenta.setVisible(true);
    }//GEN-LAST:event_jMICadastroFerramentaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
     FRMGerenciamentoFerramenta gerenciamentoFerramenta = new FRMGerenciamentoFerramenta();
    gerenciamentoFerramenta.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMIGerenciamentoFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciamentoFerramentasActionPerformed
        FRMGerenciamentoFerramenta gerenciamentoFerramenta = new FRMGerenciamentoFerramenta ();
    gerenciamentoFerramenta.setVisible(true);
    }//GEN-LAST:event_jMIGerenciamentoFerramentasActionPerformed

    private void jMICadastroAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastroAmigoActionPerformed
        FRMCadastroAmigo cadastroAmigo = new FRMCadastroAmigo ();
    cadastroAmigo.setVisible(true);
    }//GEN-LAST:event_jMICadastroAmigoActionPerformed

    private void jMIGerenciamentoAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciamentoAmigosActionPerformed
      FRMGerenciamentoAmigo gerenciamentoAmigo = new FRMGerenciamentoAmigo ();
    gerenciamentoAmigo.setVisible(true);
    }//GEN-LAST:event_jMIGerenciamentoAmigosActionPerformed

    private void jMIConcluirEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConcluirEmprestimoActionPerformed
        FRMConcluir concluirEmprestimo = new FRMConcluir();
    concluirEmprestimo.setVisible(true);
    }//GEN-LAST:event_jMIConcluirEmprestimoActionPerformed

    private void jMIRelatorioToodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioToodsActionPerformed
        FRMRelatorioTodos relatorioTodos = new FRMRelatorioTodos();
    relatorioTodos.setVisible(true);
    }//GEN-LAST:event_jMIRelatorioToodsActionPerformed

    private void jMIEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEstatisticasActionPerformed
      FRMEstatisticas estatisticas = new FRMEstatisticas();
    estatisticas.setVisible(true);
    }//GEN-LAST:event_jMIEstatisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMICadastroAmigo;
    private javax.swing.JMenuItem jMICadastroFerramenta;
    private javax.swing.JMenuItem jMIConcluirEmprestimo;
    private javax.swing.JMenuItem jMIEmprestimoFerramenta;
    private javax.swing.JMenuItem jMIEstatisticas;
    private javax.swing.JMenuItem jMIGerenciamentoAmigos;
    private javax.swing.JMenuItem jMIGerenciamentoFerramentas;
    private javax.swing.JMenuItem jMIRelatorioAtivo;
    private javax.swing.JMenuItem jMIRelatorioFerramenta;
    private javax.swing.JMenuItem jMIRelatorioToods;
    private javax.swing.JMenuItem jMITestePopUp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
